### ISSUE TITLE
Why did the "PoseScene" need "kinect"?

### ISSUE THREAD

**Issue by wo-ai-tt** [maceq687/FullBodyPoseEstimation#2]
I use  Oculus Rift S to run the Scene named “PoseScene”，for I don't have the kinect camera.I want to my webcam to do the motion capture.I can see the whole scene in my HMD，however,it put error when I click play:"Cannot find webcam device Kinect V2 Video Sensor.UnityEngine.StackTraceUtility:ExtractStackTrace ()  WebCamInput:Start () (at Assets/Scripts/WebCamInput.cs:28)." I can press "space" key and "g" key,it can also give feedback,but just can't call my webcam.
How can I slove the error？Please give me some suggestions

**Comment by maceq687** [comment]
Hi @wo-ai-tt
You don't specifically need Kinect for the PoseScene, it should work with any kind of webcam. This error might have happened because last time when that scene was saved it seem that the Kinect camera was used.

**Solution:**

1. Open the `WebCamInput` prefab in the PoseScene hierarchy

![PoseHier](https://user-images.githubusercontent.com/16693084/222102342-31cd7759-4748-47eb-8369-f37779717d92.PNG)

2. Select your preferred webcam input from the `Web Cam Name` dropdown (content of this list might be different for you, it depends on the available camera sources available on your computer)

![PoseWebCam](https://user-images.githubusercontent.com/16693084/222102362-bf6ca18e-657a-459e-9427-732d6b8e6016.PNG)

Let me know if this have solved your problem

**Comment by wo-ai-tt** [comment]
> Hi @wo-ai-tt You don't specifically need Kinect for the PoseScene, it should work with any kind of webcam. This error might have happened because last time when that scene was saved it seem that the Kinect camera was used.
> 
> **Solution:**
> 
> 1. Open the `WebCamInput` prefab in the PoseScene hierarchy
> 
> ![PoseHier](https://user-images.githubusercontent.com/16693084/222102342-31cd7759-4748-47eb-8369-f37779717d92.PNG)
> 
> 2. Select your preferred webcam input from the `Web Cam Name` dropdown (content of this list might be different for you, it depends on the available camera sources available on your computer)
> 
> ![PoseWebCam](https://user-images.githubusercontent.com/16693084/222102362-bf6ca18e-657a-459e-9427-732d6b8e6016.PNG)
> 
> Let me know if this have solved your problem

I am very glad that you can reply to my issue in time. According to your method, the scene can indeed run without error. The webcam scene does do motion capture. However, I had to use the "space" and "g" keys to calibrate and display the mirror. Is it because my device is Rift S that I can't use the buttons of the VR controller?

**Comment by maceq687** [comment]
I'm glad that it did fix your problem.
As for the calibration and mirror switching, during development of the project we were working with Quest 2 and it was working fine, I believe it should work with Rift S's Touch controllers X/A buttons as well but I can not vouch for that.
